# Generated by Django 5.2.8 on 2025-11-17 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('LISTO_RETIRAR', 'Listo para Retirar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20, verbose_name='Estado del Pedido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Pedido')),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo Total')),
            ],
            options={
                'verbose_name': 'Pedido de Cliente',
                'verbose_name_plural': 'Pedidos de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Solicitada')),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio en el momento del Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
