# Generated by Django 5.2.8 on 2025-11-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Unitario')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('esta_disponible', models.BooleanField(default=True, verbose_name='Disponible para Venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Cantina',
                'verbose_name_plural': 'Productos de Cantina',
                'ordering': ['nombre'],
            },
        ),
    ]
